# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f89c0ae58b5ec614c93f97f30d6067b866d64739f223dfbc249eeb7683d0e0cbab8fb26075543a5d47a537caa0c1e21ecb52d82750591099c26b8fa675aee5d4

test:
  secret_key_base: dcc10a5824b7fc78b3c6522968e2338414cfb994a8c39d321b2ad80e93c2beb982429280bddf4894d5fc33da0923c0fe050c3fa8960e34ed19b489306cd3cba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
